collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3051052
  brandStrength: 0.3754028
  lightness: 0.2798461
  brandColors:
    - '#5C391F'
    - '#201D17'
    - '#CFC5B3'
    - '#915B42'
    - '#EFF4F8'
  rhythmicContrast: 0.9794636
typography_spectrum: 0.385324
layout_spectrum: 0.7320086
name: BruceSchultz
